- name: alp
  shell: cat /var/log/nginx/access.log | alp ltsv -r --sort sum -m '/api/user/reservations/[0-9]+/cancel','/api/user/reservations/[0-9]+','/fonts/*','/js/*','/profile/*','/css/*' > /tmp/alp.txt

- name: Download access log
  fetch:
    src: /tmp/alp.txt
    dest: /tmp
