version: '3'

services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
      - ./frontend/dist:/opt/isucon/public
    ports:
      - "8080:80"
      #- "5000:5000"
    links:
      - "webapp"
#      - "payment"
