version: '3'

services:
  mysql:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - "TZ=Asia/Tokyo"
    env_file:
      - ".env"
    volumes:
      - mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - /var/log/mysql:/var/log/mysql
    # development only
    ports:
      - "3306:3306"

  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/conf.d/lb.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
      - ./frontend/dist:/opt/isucon/public
    ports:
      - "8080:80"
      #- "5000:5000"
volumes:
  mysql:
